spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/butim
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

external:
  industrial-accident:
    base-url: https://apis.data.go.kr/B490001/SJBoheomYoyang
    service-key: ${SERVICE_KEY}
    page-no: 1
    num-of-rows: 10000
    industry-path: /OPA001MT_12_INFO
    job-path: /OPA252MT_14_INFO
